In [1]:
!which python

/usr/WS2/iopp/software/venvs/h5bench-py/bin/python

In [2]:
import darshan

In [3]:
log="/usr/workspace/iopp/software/h5intent/h5bench/darshan-logs/sync_1_4_libdarshan/sync-write-2d-contig-contig/haridev_h5bench_write_id154479-154479_11-2-69385-16550640230916543390_1.darshan"

In [4]:
report = darshan.DarshanReport(log, read_all=True)  # Default behavior
report.info()

Filename:       /usr/workspace/iopp/software/h5intent/h5bench/darshan-logs/sync_1_4_libdarshan/sync-write-2d-contig-contig/haridev_h5bench_write_id154479-154479_11-2-69385-16550640230916543390_1.darshan
Times:          2022-11-02 19:16:25 to 2022-11-02 19:16:31 (Duration 0:00:06)
Executable:    h5bench_write /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/55c2f22c/h5bench.cfg /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5
Processes:      4
JobID:          154479
UID:            35619
Modules in Log: ['POSIX', 'MPI-IO', 'H5F', 'H5D', 'STDIO', 'HEATMAP']
Loaded Records: {'POSIX': 1, 'MPI-IO': 1, 'H5F': 1, 'H5D': 40, 'STDIO': 3}
Name Records:   49
Darshan/Hints:  {'lib_ver': '3.4.0', 'h': 'romio_no_indep_rw=true;cb_nodes=4'}
DarshanReport:  id(35219813466944) (tmp)

In [5]:
num_processes = report.data['metadata']['job']['nprocs']
print(f'num_processes {num_processes}')

num_processes 4

In [6]:
report.modules

{'POSIX': {'len': 233,
  'ver': 4,
  'idx': 1,
  'partial_flag': False,
  'num_records': 1},
 'MPI-IO': {'len': 148,
  'ver': 3,
  'idx': 2,
  'partial_flag': False,
  'num_records': 1},
 'H5F': {'len': 55,
  'ver': 3,
  'idx': 3,
  'partial_flag': False,
  'num_records': 1},
 'H5D': {'len': 2872,
  'ver': 2,
  'idx': 4,
  'partial_flag': False,
  'num_records': 40},
 'STDIO': {'len': 222,
  'ver': 2,
  'idx': 8,
  'partial_flag': False,
  'num_records': 3},
 'HEATMAP': {'len': 804, 'ver': 1, 'idx': 14, 'partial_flag': False}}

In [7]:
report.data.keys()

dict_keys(['version', 'metadata', 'records', 'summary', 'modules', 'counters', 'name_records', 'mounts'])

In [8]:
report.data['name_records']

{14734109647742566553: '<STDIN>',
 15920181672442173319: '<STDOUT>',
 7238257241479193519: '<STDERR>',
 3989511027826779520: 'heatmap:STDIO',
 12341684537064948355: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/55c2f22c/h5bench.cfg',
 8506552128164983584: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/55c2f22c/output.csv',
 16592106915301738621: 'heatmap:POSIX',
 8056340912518900982: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5',
 3668870418325792824: 'heatmap:MPIIO',
 16745377055716447980: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_0x',
 9232474897724205454: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_0y',
 9666922823116067007: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_0z',
 7954294605057424772: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_0px',
 14559898599824878032: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_0py',
 14053220335450058874: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_0pz',
 3583550608530208099: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_0id_1',
 12492818401624524894: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_0id_2',
 6337345834477782232: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_1x',
 587337484414354875: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_1y',
 17088026222374296832: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_1z',
 10365868965073833063: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_1px',
 1367249824142530829: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_1py',
 11281992775688983841: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_1pz',
 16506597215654352263: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_1id_1',
 2072042114563608409: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_1id_2',
 449811033396935019: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_2x',
 824375428182222914: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_2y',
 15636447173008133680: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_2z',
 14567530470015239051: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_2px',
 13226748278729267481: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_2py',
 3027041011079631012: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_2pz',
 8535147560700606874: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_2id_1',
 17448762730142024018: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_2id_2',
 9231820324891197767: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_3x',
 10073633638389463854: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_3y',
 2262910115192262680: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_3z',
 6698652186124638899: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_3px',
 13982549373984521618: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_3py',
 10126444151723262841: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_3pz',
 11408524144203286521: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_3id_1',
 12481406429664800494: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_3id_2',
 13087343237781170849: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_4x',
 1518489533526045308: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_4y',
 16473310340313501291: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_4z',
 4476712986536512531: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_4px',
 679650517378964338: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_4py',
 11400354699856753065: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_4pz',
 12887863828293197115: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_4id_1',
 5612277294070424906: '/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_4id_2'}

In [49]:
relevant_ids = []
name_to_id_map = {}
for key, value in report.data['name_records'].items():
    if "/p/gpfs1" in value:
        relevant_ids.append(key)
        print(key,value)
        name_to_id_map[value] = key

12341684537064948355 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/55c2f22c/h5bench.cfg
8506552128164983584 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/55c2f22c/output.csv
8056340912518900982 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5
16745377055716447980 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_0x
9232474897724205454 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_0y
9666922823116067007 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_0z
7954294605057424772 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_0px
14559898599824878032 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_0py
14053220335450058874 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_0pz
3583550608530208099 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_0id_1
12492818401624524894 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_0id_2
6337345834477782232 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_1x
587337484414354875 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_1y
17088026222374296832 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_1z
10365868965073833063 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_1px
1367249824142530829 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_1py
11281992775688983841 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_1pz
16506597215654352263 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_1id_1
2072042114563608409 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_1id_2
449811033396935019 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_2x
824375428182222914 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_2y
15636447173008133680 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_2z
14567530470015239051 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_2px
13226748278729267481 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_2py
3027041011079631012 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_2pz
8535147560700606874 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_2id_1
17448762730142024018 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_2id_2
9231820324891197767 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_3x
10073633638389463854 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_3y
2262910115192262680 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_3z
6698652186124638899 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_3px
13982549373984521618 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_3py
10126444151723262841 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_3pz
11408524144203286521 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_3id_1
12481406429664800494 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_3id_2
13087343237781170849 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_4x
1518489533526045308 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_4y
16473310340313501291 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_4z
4476712986536512531 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_4px
679650517378964338 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_4py
11400354699856753065 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_4pz
12887863828293197115 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_4id_1
5612277294070424906 /p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_4id_2

In [10]:
relevant_ids

[12341684537064948355,
 8506552128164983584,
 8056340912518900982,
 16745377055716447980,
 9232474897724205454,
 9666922823116067007,
 7954294605057424772,
 14559898599824878032,
 14053220335450058874,
 3583550608530208099,
 12492818401624524894,
 6337345834477782232,
 587337484414354875,
 17088026222374296832,
 10365868965073833063,
 1367249824142530829,
 11281992775688983841,
 16506597215654352263,
 2072042114563608409,
 449811033396935019,
 824375428182222914,
 15636447173008133680,
 14567530470015239051,
 13226748278729267481,
 3027041011079631012,
 8535147560700606874,
 17448762730142024018,
 9231820324891197767,
 10073633638389463854,
 2262910115192262680,
 6698652186124638899,
 13982549373984521618,
 10126444151723262841,
 11408524144203286521,
 12481406429664800494,
 13087343237781170849,
 1518489533526045308,
 16473310340313501291,
 4476712986536512531,
 679650517378964338,
 11400354699856753065,
 12887863828293197115,
 5612277294070424906]

In [11]:
report.mod_read_all_records('POSIX')
report.mod_read_all_records('STDIO')
report.mod_read_all_records('MPI-IO')
report.mod_read_all_records('H5F')
report.mod_read_all_records('H5D')

In [12]:
posix_df_c = report.records['POSIX'].to_df()['counters']
mpiio_df_c = report.records['MPI-IO'].to_df()['counters']
stdio_df_c = report.records['STDIO'].to_df()['counters']
h5f_df_c = report.records['H5F'].to_df()['counters']
h5d_df_c = report.records['H5D'].to_df()['counters']

In [13]:
posix_df_fc = report.records['POSIX'].to_df()['fcounters']
mpiio_df_fc = report.records['MPI-IO'].to_df()['fcounters']
stdio_df_fc = report.records['STDIO'].to_df()['fcounters']
h5f_df_fc = report.records['H5F'].to_df()['fcounters']
h5d_df_fc = report.records['H5D'].to_df()['fcounters']

In [14]:
posix_df_c.dtypes

rank                        int64
id                          int64
POSIX_OPENS                 int64
POSIX_FILENOS               int64
POSIX_DUPS                  int64
                            ...
POSIX_ACCESS4_COUNT         int64
POSIX_FASTEST_RANK          int64
POSIX_FASTEST_RANK_BYTES    int64
POSIX_SLOWEST_RANK          int64
POSIX_SLOWEST_RANK_BYTES    int64
Length: 71, dtype: object

In [15]:
rel_posix_df_c = posix_df_c[posix_df_c['id'].isin(relevant_ids)]
rel_mpiio_df_c = mpiio_df_c[mpiio_df_c['id'].isin(relevant_ids)]
rel_stdio_df_c = stdio_df_c[stdio_df_c['id'].isin(relevant_ids)]
h5f_df_c = h5f_df_c[h5f_df_c['id'].isin(relevant_ids)]
h5d_df_c = h5d_df_c[h5d_df_c['id'].isin(relevant_ids)]

rel_posix_df_fc = posix_df_fc[posix_df_fc['id'].isin(relevant_ids)]
rel_mpiio_df_fc = mpiio_df_fc[mpiio_df_fc['id'].isin(relevant_ids)]
rel_stdio_df_fc = stdio_df_fc[stdio_df_fc['id'].isin(relevant_ids)]
h5f_df_fc = h5f_df_fc[h5f_df_fc['id'].isin(relevant_ids)]
h5d_df_fc = h5d_df_fc[h5d_df_fc['id'].isin(relevant_ids)]

In [16]:
rel_posix_df_c

,rank,id,POSIX_OPENS,POSIX_FILENOS,POSIX_DUPS,POSIX_READS,POSIX_WRITES,POSIX_SEEKS,POSIX_STATS,POSIX_MMAPS,...,POSIX_ACCESS3_ACCESS,POSIX_ACCESS4_ACCESS,POSIX_ACCESS1_COUNT,POSIX_ACCESS2_COUNT,POSIX_ACCESS3_COUNT,POSIX_ACCESS4_COUNT,POSIX_FASTEST_RANK,POSIX_FASTEST_RANK_BYTES,POSIX_SLOWEST_RANK,POSIX_SLOWEST_RANK_BYTES
0,-1,8056340912518900982,5,0,0,12,172,3,2,-1,...,2000,1904,160,16,2,2,1,169873120,0,168824736

In [17]:
rel_posix_df_fc

,rank,id,POSIX_F_OPEN_START_TIMESTAMP,POSIX_F_READ_START_TIMESTAMP,POSIX_F_WRITE_START_TIMESTAMP,POSIX_F_CLOSE_START_TIMESTAMP,POSIX_F_OPEN_END_TIMESTAMP,POSIX_F_READ_END_TIMESTAMP,POSIX_F_WRITE_END_TIMESTAMP,POSIX_F_CLOSE_END_TIMESTAMP,POSIX_F_READ_TIME,POSIX_F_WRITE_TIME,POSIX_F_META_TIME,POSIX_F_MAX_READ_TIME,POSIX_F_MAX_WRITE_TIME,POSIX_F_FASTEST_RANK_TIME,POSIX_F_SLOWEST_RANK_TIME,POSIX_F_VARIANCE_RANK_TIME,POSIX_F_VARIANCE_RANK_BYTES
0,-1,8056340912518900982,0.352706,5.067459,0.354467,0.352927,0.353,5.07223,5.072241,0.352937,0.002666,1.415453,0.00047,0.000905,0.076821,0.091461,0.667334,0.058122,5.479458e+11

In [18]:
rel_mpiio_df_c

,rank,id,MPIIO_INDEP_OPENS,MPIIO_COLL_OPENS,MPIIO_INDEP_READS,MPIIO_INDEP_WRITES,MPIIO_COLL_READS,MPIIO_COLL_WRITES,MPIIO_SPLIT_READS,MPIIO_SPLIT_WRITES,...,MPIIO_ACCESS3_ACCESS,MPIIO_ACCESS4_ACCESS,MPIIO_ACCESS1_COUNT,MPIIO_ACCESS2_COUNT,MPIIO_ACCESS3_COUNT,MPIIO_ACCESS4_COUNT,MPIIO_FASTEST_RANK,MPIIO_FASTEST_RANK_BYTES,MPIIO_SLOWEST_RANK,MPIIO_SLOWEST_RANK_BYTES
0,-1,8056340912518900982,0,4,0,0,0,164,0,0,...,4392,4104,160,1,1,1,1,167776152,2,167776552

In [19]:
rel_mpiio_df_fc

,rank,id,MPIIO_F_OPEN_START_TIMESTAMP,MPIIO_F_READ_START_TIMESTAMP,MPIIO_F_WRITE_START_TIMESTAMP,MPIIO_F_CLOSE_START_TIMESTAMP,MPIIO_F_OPEN_END_TIMESTAMP,MPIIO_F_READ_END_TIMESTAMP,MPIIO_F_WRITE_END_TIMESTAMP,MPIIO_F_CLOSE_END_TIMESTAMP,MPIIO_F_READ_TIME,MPIIO_F_WRITE_TIME,MPIIO_F_META_TIME,MPIIO_F_MAX_READ_TIME,MPIIO_F_MAX_WRITE_TIME,MPIIO_F_FASTEST_RANK_TIME,MPIIO_F_SLOWEST_RANK_TIME,MPIIO_F_VARIANCE_RANK_TIME,MPIIO_F_VARIANCE_RANK_BYTES
0,-1,8056340912518900982,0.339723,0.0,0.353898,0.0,0.353081,0.0,5.072249,0.0,0.0,2.786683,0.053281,0.0,0.078708,0.539815,0.966311,0.026721,71472.0

In [20]:
rel_stdio_df_c

,rank,id,STDIO_OPENS,STDIO_FDOPENS,STDIO_READS,STDIO_WRITES,STDIO_SEEKS,STDIO_FLUSHES,STDIO_BYTES_WRITTEN,STDIO_BYTES_READ,STDIO_MAX_BYTE_READ,STDIO_MAX_BYTE_WRITTEN,STDIO_FASTEST_RANK,STDIO_FASTEST_RANK_BYTES,STDIO_SLOWEST_RANK,STDIO_SLOWEST_RANK_BYTES
0,-1,8506552128164983584,4,0,0,13,0,0,309,0,0,308,2,0,0,309
1,-1,12341684537064948355,4,0,48,0,0,0,0,1140,284,0,0,285,1,285

In [21]:
rel_stdio_df_fc

,rank,id,STDIO_F_META_TIME,STDIO_F_WRITE_TIME,STDIO_F_READ_TIME,STDIO_F_OPEN_START_TIMESTAMP,STDIO_F_CLOSE_START_TIMESTAMP,STDIO_F_WRITE_START_TIMESTAMP,STDIO_F_READ_START_TIMESTAMP,STDIO_F_OPEN_END_TIMESTAMP,STDIO_F_CLOSE_END_TIMESTAMP,STDIO_F_WRITE_END_TIMESTAMP,STDIO_F_READ_END_TIMESTAMP,STDIO_F_FASTEST_RANK_TIME,STDIO_F_SLOWEST_RANK_TIME,STDIO_F_VARIANCE_RANK_TIME,STDIO_F_VARIANCE_RANK_BYTES
0,-1,8506552128164983584,0.002177,0.000031,0.000000,0.061653,5.460315,5.460277,0.000000,0.062279,5.460463,5.460315,0.000000,0.000454,0.000682,7.290652e-09,17902.6875
1,-1,12341684537064948355,0.000134,0.000000,0.000102,0.061537,0.000000,0.000000,0.061599,0.061734,0.000000,0.000000,0.061774,0.000042,0.000083,2.781206e-10,0.0000

In [22]:
h5f_df_c

   rank                   id  H5F_OPENS  H5F_FLUSHES  H5F_USE_MPIIO
0    -1  8056340912518900982          4            4              1

In [23]:
h5f_df_fc

,rank,id,H5F_F_OPEN_START_TIMESTAMP,H5F_F_CLOSE_START_TIMESTAMP,H5F_F_OPEN_END_TIMESTAMP,H5F_F_CLOSE_END_TIMESTAMP,H5F_F_META_TIME
0,-1,8056340912518900982,0.325246,5.460235,0.353426,5.460251,1.670914

In [48]:
h5d_df_c

,rank,id,H5D_OPENS,H5D_READS,H5D_WRITES,H5D_FLUSHES,H5D_BYTES_READ,H5D_BYTES_WRITTEN,H5D_RW_SWITCHES,H5D_REGULAR_HYPERSLAB_SELECTS,...,H5D_CHUNK_SIZE_D2,H5D_CHUNK_SIZE_D3,H5D_CHUNK_SIZE_D4,H5D_CHUNK_SIZE_D5,H5D_USE_MPIIO_COLLECTIVE,H5D_USE_DEPRECATED,H5D_FASTEST_RANK,H5D_FASTEST_RANK_BYTES,H5D_SLOWEST_RANK,H5D_SLOWEST_RANK_BYTES
0,-1,449811033396935019,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,3,4194304,1,4194304
1,-1,587337484414354875,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,0,4194304,1,4194304
2,-1,679650517378964338,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,1,4194304,3,4194304
3,-1,824375428182222914,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,2,4194304,0,4194304
4,-1,1367249824142530829,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,1,4194304,3,4194304
5,-1,1518489533526045308,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,1,4194304,3,4194304
6,-1,2072042114563608409,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,0,4194304,2,4194304
7,-1,2262910115192262680,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,0,4194304,3,4194304
8,-1,3027041011079631012,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,1,4194304,3,4194304
9,-1,3583550608530208099,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,0,4194304,3,4194304
10,-1,4476712986536512531,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,1,4194304,3,4194304
11,-1,5612277294070424906,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,1,4194304,3,4194304
12,-1,6337345834477782232,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,0,4194304,3,4194304
13,-1,6698652186124638899,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,1,4194304,3,4194304
14,-1,7954294605057424772,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,3,4194304,0,4194304
15,-1,8535147560700606874,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,1,4194304,2,4194304
16,-1,9231820324891197767,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,3,4194304,1,4194304
17,-1,9232474897724205454,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,1,4194304,3,4194304
18,-1,9666922823116067007,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,3,4194304,0,4194304
19,-1,10073633638389463854,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,1,4194304,3,4194304
20,-1,10126444151723262841,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,0,4194304,3,4194304
21,-1,10365868965073833063,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,1,4194304,0,4194304
22,-1,11281992775688983841,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,1,4194304,3,4194304
23,-1,11400354699856753065,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,1,4194304,3,4194304
24,-1,11408524144203286521,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,0,4194304,3,4194304
25,-1,12481406429664800494,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,0,4194304,3,4194304
26,-1,12492818401624524894,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,0,4194304,3,4194304
27,-1,12887863828293197115,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,2,4194304,3,4194304
28,-1,13087343237781170849,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,0,4194304,3,4194304
29,-1,13226748278729267481,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,0,4194304,3,4194304
30,-1,13982549373984521618,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,1,4194304,0,4194304
31,-1,14053220335450058874,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,3,4194304,1,4194304
32,-1,14559898599824878032,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,3,4194304,1,4194304
33,-1,14567530470015239051,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,1,4194304,0,4194304
34,-1,15636447173008133680,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,0,4194304,3,4194304
35,-1,16473310340313501291,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,3,4194304,0,4194304
36,-1,16506597215654352263,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,0,4194304,3,4194304
37,-1,16745377055716447980,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,0,4194304,3,4194304
38,-1,17088026222374296832,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,1,4194304,3,4194304
39,-1,17448762730142024018,4,0,4,0,0,16777216,0,4,...,0,0,0,0,1,0,0,4194304,2,4194304

In [24]:
h5d_df_c[['H5D_USE_MPIIO_COLLECTIVE','H5D_DATATYPE_SIZE','H5D_DATASPACE_NDIMS','H5D_ACCESS1_ACCESS','H5D_ACCESS1_COUNT','H5D_ACCESS1_LENGTH_D5','H5D_ACCESS1_LENGTH_D4','H5D_DATASPACE_NPOINTS']]

,H5D_USE_MPIIO_COLLECTIVE,H5D_DATATYPE_SIZE,H5D_DATASPACE_NDIMS,H5D_ACCESS1_ACCESS,H5D_ACCESS1_COUNT,H5D_ACCESS1_LENGTH_D5,H5D_ACCESS1_LENGTH_D4,H5D_DATASPACE_NPOINTS
0,1,4,2,4194304,4,1024,1024,4194304
1,1,4,2,4194304,4,1024,1024,4194304
2,1,4,2,4194304,4,1024,1024,4194304
3,1,4,2,4194304,4,1024,1024,4194304
4,1,4,2,4194304,4,1024,1024,4194304
5,1,4,2,4194304,4,1024,1024,4194304
6,1,4,2,4194304,4,1024,1024,4194304
7,1,4,2,4194304,4,1024,1024,4194304
8,1,4,2,4194304,4,1024,1024,4194304
9,1,4,2,4194304,4,1024,1024,4194304
10,1,4,2,4194304,4,1024,1024,4194304
11,1,4,2,4194304,4,1024,1024,4194304
12,1,4,2,4194304,4,1024,1024,4194304
13,1,4,2,4194304,4,1024,1024,4194304
14,1,4,2,4194304,4,1024,1024,4194304
15,1,4,2,4194304,4,1024,1024,4194304
16,1,4,2,4194304,4,1024,1024,4194304
17,1,4,2,4194304,4,1024,1024,4194304
18,1,4,2,4194304,4,1024,1024,4194304
19,1,4,2,4194304,4,1024,1024,4194304
20,1,4,2,4194304,4,1024,1024,4194304
21,1,4,2,4194304,4,1024,1024,4194304
22,1,4,2,4194304,4,1024,1024,4194304
23,1,4,2,4194304,4,1024,1024,4194304
24,1,4,2,4194304,4,1024,1024,4194304
25,1,4,2,4194304,4,1024,1024,4194304
26,1,4,2,4194304,4,1024,1024,4194304
27,1,4,2,4194304,4,1024,1024,4194304
28,1,4,2,4194304,4,1024,1024,4194304
29,1,4,2,4194304,4,1024,1024,4194304
30,1,4,2,4194304,4,1024,1024,4194304
31,1,4,2,4194304,4,1024,1024,4194304
32,1,4,2,4194304,4,1024,1024,4194304
33,1,4,2,4194304,4,1024,1024,4194304
34,1,4,2,4194304,4,1024,1024,4194304
35,1,4,2,4194304,4,1024,1024,4194304
36,1,4,2,4194304,4,1024,1024,4194304
37,1,4,2,4194304,4,1024,1024,4194304
38,1,4,2,4194304,4,1024,1024,4194304
39,1,4,2,4194304,4,1024,1024,4194304

In [42]:
h5d_df_fc.columns

Index(['rank', 'id', 'H5D_F_OPEN_START_TIMESTAMP',
       'H5D_F_READ_START_TIMESTAMP', 'H5D_F_WRITE_START_TIMESTAMP',
       'H5D_F_CLOSE_START_TIMESTAMP', 'H5D_F_OPEN_END_TIMESTAMP',
       'H5D_F_READ_END_TIMESTAMP', 'H5D_F_WRITE_END_TIMESTAMP',
       'H5D_F_CLOSE_END_TIMESTAMP', 'H5D_F_READ_TIME', 'H5D_F_WRITE_TIME',
       'H5D_F_META_TIME', 'H5D_F_MAX_READ_TIME', 'H5D_F_MAX_WRITE_TIME',
       'H5D_F_FASTEST_RANK_TIME', 'H5D_F_SLOWEST_RANK_TIME',
       'H5D_F_VARIANCE_RANK_TIME', 'H5D_F_VARIANCE_RANK_BYTES'],
      dtype='object')

In [44]:
h5d_df_c.columns

Index(['rank', 'id', 'H5D_OPENS', 'H5D_READS', 'H5D_WRITES', 'H5D_FLUSHES',
       'H5D_BYTES_READ', 'H5D_BYTES_WRITTEN', 'H5D_RW_SWITCHES',
       'H5D_REGULAR_HYPERSLAB_SELECTS', 'H5D_IRREGULAR_HYPERSLAB_SELECTS',
       'H5D_POINT_SELECTS', 'H5D_MAX_READ_TIME_SIZE',
       'H5D_MAX_WRITE_TIME_SIZE', 'H5D_SIZE_READ_AGG_0_100',
       'H5D_SIZE_READ_AGG_100_1K', 'H5D_SIZE_READ_AGG_1K_10K',
       'H5D_SIZE_READ_AGG_10K_100K', 'H5D_SIZE_READ_AGG_100K_1M',
       'H5D_SIZE_READ_AGG_1M_4M', 'H5D_SIZE_READ_AGG_4M_10M',
       'H5D_SIZE_READ_AGG_10M_100M', 'H5D_SIZE_READ_AGG_100M_1G',
       'H5D_SIZE_READ_AGG_1G_PLUS', 'H5D_SIZE_WRITE_AGG_0_100',
       'H5D_SIZE_WRITE_AGG_100_1K', 'H5D_SIZE_WRITE_AGG_1K_10K',
       'H5D_SIZE_WRITE_AGG_10K_100K', 'H5D_SIZE_WRITE_AGG_100K_1M',
       'H5D_SIZE_WRITE_AGG_1M_4M', 'H5D_SIZE_WRITE_AGG_4M_10M',
       'H5D_SIZE_WRITE_AGG_10M_100M', 'H5D_SIZE_WRITE_AGG_100M_1G',
       'H5D_SIZE_WRITE_AGG_1G_PLUS', 'H5D_ACCESS1_ACCESS',
       'H5D_ACCESS1_LENGTH_D1', 'H5D_ACCESS1_LENGTH_D2',
       'H5D_ACCESS1_LENGTH_D3', 'H5D_ACCESS1_LENGTH_D4',
       'H5D_ACCESS1_LENGTH_D5', 'H5D_ACCESS1_STRIDE_D1',
       'H5D_ACCESS1_STRIDE_D2', 'H5D_ACCESS1_STRIDE_D3',
       'H5D_ACCESS1_STRIDE_D4', 'H5D_ACCESS1_STRIDE_D5', 'H5D_ACCESS2_ACCESS',
       'H5D_ACCESS2_LENGTH_D1', 'H5D_ACCESS2_LENGTH_D2',
       'H5D_ACCESS2_LENGTH_D3', 'H5D_ACCESS2_LENGTH_D4',
       'H5D_ACCESS2_LENGTH_D5', 'H5D_ACCESS2_STRIDE_D1',
       'H5D_ACCESS2_STRIDE_D2', 'H5D_ACCESS2_STRIDE_D3',
       'H5D_ACCESS2_STRIDE_D4', 'H5D_ACCESS2_STRIDE_D5', 'H5D_ACCESS3_ACCESS',
       'H5D_ACCESS3_LENGTH_D1', 'H5D_ACCESS3_LENGTH_D2',
       'H5D_ACCESS3_LENGTH_D3', 'H5D_ACCESS3_LENGTH_D4',
       'H5D_ACCESS3_LENGTH_D5', 'H5D_ACCESS3_STRIDE_D1',
       'H5D_ACCESS3_STRIDE_D2', 'H5D_ACCESS3_STRIDE_D3',
       'H5D_ACCESS3_STRIDE_D4', 'H5D_ACCESS3_STRIDE_D5', 'H5D_ACCESS4_ACCESS',
       'H5D_ACCESS4_LENGTH_D1', 'H5D_ACCESS4_LENGTH_D2',
       'H5D_ACCESS4_LENGTH_D3', 'H5D_ACCESS4_LENGTH_D4',
       'H5D_ACCESS4_LENGTH_D5', 'H5D_ACCESS4_STRIDE_D1',
       'H5D_ACCESS4_STRIDE_D2', 'H5D_ACCESS4_STRIDE_D3',
       'H5D_ACCESS4_STRIDE_D4', 'H5D_ACCESS4_STRIDE_D5', 'H5D_ACCESS1_COUNT',
       'H5D_ACCESS2_COUNT', 'H5D_ACCESS3_COUNT', 'H5D_ACCESS4_COUNT',
       'H5D_DATASPACE_NDIMS', 'H5D_DATASPACE_NPOINTS', 'H5D_DATATYPE_SIZE',
       'H5D_CHUNK_SIZE_D1', 'H5D_CHUNK_SIZE_D2', 'H5D_CHUNK_SIZE_D3',
       'H5D_CHUNK_SIZE_D4', 'H5D_CHUNK_SIZE_D5', 'H5D_USE_MPIIO_COLLECTIVE',
       'H5D_USE_DEPRECATED', 'H5D_FASTEST_RANK', 'H5D_FASTEST_RANK_BYTES',
       'H5D_SLOWEST_RANK', 'H5D_SLOWEST_RANK_BYTES'],
      dtype='object')

In [45]:
h5f_df_c

   rank                   id  H5F_OPENS  H5F_FLUSHES  H5F_USE_MPIIO
0    -1  8056340912518900982          4            4              1

In [46]:
h5f_df_fc

,rank,id,H5F_F_OPEN_START_TIMESTAMP,H5F_F_CLOSE_START_TIMESTAMP,H5F_F_OPEN_END_TIMESTAMP,H5F_F_CLOSE_END_TIMESTAMP,H5F_F_META_TIME
0,-1,8056340912518900982,0.325246,5.460235,0.353426,5.460251,1.670914

In [53]:
class DatasetAccessProperties:
    def __init__(self):
        self.append_flush = None
        self.chunk_cache = None
        self.virtual_view = None
        self.filter_avail = None
        self.gzip = None
        self.layout = None
        self.chunk = None
        self.szip = None
    def __repr__ (self):
        return str(json())
    def json(self):
        return {
           'append_flush': self.append_flush,
           'chunk_cache': self.chunk_cache,
           'virtual_view': self.virtual_view,
           'filter_avail': self.filter_avail,
           'gzip': self.gzip, 
           'layout': self.layout,
           'chunk': self.chunk,
           'szip': self.szip, 
        }
class DatasetTransferProperties:
    def __init__(self):
        self.mpiio = None
        self.buffer = None
        self.edc_check = None
        self.hyper_vector = None
        self.mem_manager = None
        self.dataset_io_hyperslab_selection = None
    def __repr__ (self):
        return str(json())
    def json (self):
        return {
           'mpiio': self.mpiio,
           'buffer': self.buffer,
           'edc_check': self.edc_check,
           'hyper_vector': self.hyper_vector,
           'mem_manager': self.mem_manager, 
           'dataset_io_hyperslab_selection': self.dataset_io_hyperslab_selection
        }

class DataSet:
    def __init__(self):
        self.filename = None
        self.dataset_name = None
        self.access = DatasetAccessProperties()
        self.transfer = DatasetTransferProperties()
    def __repr__ (self):
        return str(json())
    def json (self):
        return {
           'filename': self.filename,
           'dataset_name': self.dataset_name,
           'access': self.access.json(),
           'transfer': self.transfer.json()
        }

In [55]:
GB=1024*1024*1024
AVAIL_NODE_MEMORY_BYTES=200*GB

In [64]:
configuration = {
    'datasets': {},
    'files':{}
}
file_agg = {}
for ind in h5d_df_c.index:
    ds_id = h5d_df_c['id'][ind]
    dataset_fqn = report.data['name_records'][ds_id]
    dataset = DataSet()
    dset_split_fqn = dataset_fqn.split(":")
    dataset.filename = dset_split_fqn[0]
    file_id = name_to_id_map[dataset.filename]
    if file_id not in file_agg:
        file_agg[file_id] = {
            'file_size':0,
            'write-only': True,
            'read-only': True,
            'raw': False,
            'close': 0,
            'ts_sum':0,
            'ts_count':0
            
        }
    file_agg[file_id]['close'] = h5d_df_fc['H5D_F_CLOSE_END_TIMESTAMP'][ind] if h5d_df_fc['H5D_F_CLOSE_END_TIMESTAMP'][ind] > file_agg[file_id]['close'] else  file_agg[file_id]['close']
    file_agg[file_id]['file_size'] = file_agg[file_id]['file_size'] + h5d_df_c['H5D_BYTES_WRITTEN'][ind]
    
    dataset.dataset_name = dset_split_fqn[1]
    dtype_size = h5d_df_c['H5D_DATATYPE_SIZE'][ind]
    num_elements_written = h5d_df_c['H5D_BYTES_WRITTEN'][ind] / dtype_size
    num_elements_read = h5d_df_c['H5D_BYTES_READ'][ind] / dtype_size
    
    if num_elements_written == 0 and num_elements_read > 0:
        file_agg[file_id]['write-only'] = False
    else:
        file_agg[file_id]['read-only'] = False
        
    if h5d_df_fc['H5D_F_READ_START_TIMESTAMP'][ind] > h5d_df_fc['H5D_F_WRITE_END_TIMESTAMP'][ind]:
        file_agg[file_id]['raw'] = True
    
    ndims = h5d_df_c['H5D_DATASPACE_NDIMS'][ind]
    boundary = [0]*ndims
    chunks = [0]*ndims
    stride = [0]*ndims
    start = [0]*ndims
    count = [h5d_df_c['H5D_ACCESS1_COUNT'][ind]]*ndims
    ts = 1
    for dim_ind in range(0,ndims):
        end_dim = 5 - dim_ind
        boundary[dim_ind] = h5d_df_c[f'H5D_ACCESS1_LENGTH_D{end_dim}'][ind] * h5d_df_c['H5D_ACCESS1_COUNT'][ind]
        chunks[dim_ind] = h5d_df_c[f'H5D_ACCESS1_LENGTH_D{end_dim}'][ind]
        stride[dim_ind] = h5d_df_c[f'H5D_ACCESS1_STRIDE_D{end_dim}'][ind]
        ts = ts * chunks[dim_ind]
    file_agg[file_id]['ts_sum'] = file_agg[file_id]['ts_sum'] + ts
    file_agg[file_id]['ts_count'] = file_agg[file_id]['ts_count'] + 1
    
    dataset.access.append_flush = { 'use': True,
                                                'ndims':ndims,
                                                'boundary':boundary
                                              }
    rdcc_w0 = 0
    
    if num_elements_read == h5d_df_c['H5D_DATASPACE_NPOINTS'][ind] or num_elements_written == h5d_df_c['H5D_DATASPACE_NPOINTS'][ind]:
        rdcc_w0 = 1
    else:
        per_re_read = h5d_df_c['H5D_DATASPACE_NPOINTS'][ind] * 1.0 /  num_elements_written
        per_re_write = h5d_df_c['H5D_DATASPACE_NPOINTS'][ind] * 1.0 /  num_elements_read
        rdcc_w0 = per_re_read if per_re_read > per_re_write else per_re_write
    dataset.access.chunk_cache = { 'use': True,
                                                'rdcc_nslots':h5d_df_c['H5D_ACCESS1_COUNT'][ind],
                                                'rdcc_nbytes':h5d_df_c['H5D_DATATYPE_SIZE'][ind] * h5d_df_c['H5D_DATASPACE_NPOINTS'][ind],
                                                'rdcc_w0':rdcc_w0
                                             }
    raw_data_size = h5d_df_c['H5D_DATASPACE_NPOINTS'][ind] * dtype_size
    layout = 0
    if raw_data_size <= 65520:
        layout = 1
    elif raw_data_size <= 4*1024*1024*1024:
        layout = 2
    else:
        layout = 3
    dataset.access.layout = {
        'use': True,
        'layout':layout
    }
    dataset.access.chunk = {
        'use': True,
        'ndims':ndims,
        'dim':chunks,
    }
    procs_accessing_ds = 1
    if h5d_df_c['rank'][ind] == -1:
        procs_accessing_ds = num_processes
     
    dataset.transfer.mpiio = {
        'use': True,
        'xfer_mode': h5d_df_c['H5D_USE_MPIIO_COLLECTIVE'][ind],
        'coll_opt_mode': h5d_df_c['H5D_USE_MPIIO_COLLECTIVE'][ind],
        # TODO(hari): set chunk_opt_mode
        'num_chunk_per_proc': h5d_df_c['H5D_ACCESS1_COUNT'][ind] / procs_accessing_ds,
        'percent_num_proc_per_chunk': procs_accessing_ds * 100 / num_processes
    }
    # TODO(hari): set this for specific apps where read needs to be correct
    dataset.transfer.edc_check = {
        'use': True,
        'check': False
    }
    dataset.transfer.hyper_vector = {
        'use': True,
        'size': h5d_df_c['H5D_DATASPACE_NPOINTS'][ind]
    }
    # TODO(hari): Check if datatype of dataset is variable on runtime.
    dataset.transfer.mem_manager = {
        'use': False
    }
    
    ops = -1
    if num_elements_written > 0 and num_elements_read ==0:
        ops = 0
    elif num_elements_read > 0 and num_elements_written ==0:
        ops = 1
    else:
        ops = 2
    
    dataset.transfer.dataset_io_hyperslab_selection = {
        'use': True,
        'rank': ndims,
        'op': ops,
        'start': start,
        'stride': stride,
        'count': count,
        'block': chunks
    }
    configuration['datasets'][dataset_fqn] = dataset

In [65]:
class FileAccessProperties:
    def __init__(self):
        self.core = None
        self.direct = None
        self.family = None
        self.log = None
        self.mpiio = None
        self.split = None
        self.stdio = None
        self.cache = None
        self.write_tracking = None
        self.close = None
        self.file_image = None
        self.optimizations = None
        self.metadata = None
        self.page_buffer = None
    def __repr__ (self):
        return str(json())
    def json (self):
        return {
           'core': self.core,
           'direct': self.direct,
           'family': self.family,
           'log': self.log,
           'mpiio': self.mpiio, 
           'split': self.split,
           'stdio': self.stdio,
           'cache': self.cache,
           'write_tracking': self.write_tracking,
           'close': self.close, 
           'file_image': self.file_image,
           'optimizations': self.optimizations,
           'metadata': self.metadata,
           'page_buffer': self.page_buffer
        }
class FileCreationProperties:
    def __init__(self):
        self.file_space = None
        self.istore = None
        self.sizes = None
    def __repr__ (self):
        return str(json())
    def json (self):
        return {
           'file_space': self.file_space,
           'istore': self.istore,
           'sizes': self.sizes,
        }         

class File:
    def __init__(self):
        self.filename = None
        self.access = FileCreationProperties()
        self.creation = FileAccessProperties()
    def __repr__ (self):
        return str(json())
    def json (self):
        return {
           'filename': self.filename,
           'access': self.access.json(),
           'creation': self.creation.json()
        }

In [67]:
for ind in h5f_df_c.index:
    file_id = h5f_df_c['id'][ind]
    file_agg_item = file_agg[file_id]
    file = File()
    file.filename = report.data['name_records'][file_id]
    
    if file_agg[file_id]['file_size'] < AVAIL_NODE_MEMORY_BYTES:
        file.access.core = {
            'use': True,
            'increment': file_agg[file_id]['file_size'],
            'backing_store': not file_agg[file_id]['read-only']
        }
    file.access.mpiio = {
            'use': True,
            'comm': 'MPI_COMM_WORLD' if h5f_df_c['rank'][ind] == -1 else 'MPI_COMM_SELF'
        }
    file.access.split = {
            'use': True if file_agg[file_id]['read-only'] else False
        }
    file.access.stdio = {
            'use': True if file_agg[file_id]['write-only'] else False
        }
    file.access.cache = {
            'use': False,
            'rdcc_nslots':0,
            'rdcc_nbytes':0,
            'rdcc_w0':0
        }
    is_stride_used = False
    for key, value in configuration['datasets'].items():
        cache = configuration['datasets'][key].access.chunk_cache
        file.access.cache['use'] = file.access.cache['use'] and cache['use']
        file.access.cache['rdcc_nslots'] = file.access.cache['rdcc_nslots'] + cache['rdcc_nslots']
        file.access.cache['rdcc_nbytes'] = file.access.cache['rdcc_nbytes'] + cache['rdcc_nbytes']
        file.access.cache['rdcc_w0'] = max(file.access.cache['rdcc_w0'], cache['rdcc_w0'])
        hyperslab_selection = dataset.transfer.dataset_io_hyperslab_selection
        for dim in range(hyperslab_selection['rank']):
            if hyperslab_selection['stride'][dim] > 0:
                is_stride_used = True
    #TODO: write_tracking when to enable 
    file.access.close = {
            'use': True,
            'evict': True if file_agg[file_id]['read-only'] or file_agg[file_id]['write-only'] else False,
            'degree': 'H5F_CLOSE_STRONG' if file_agg[file_id]['close'] < h5f_df_fc['H5F_F_CLOSE_END_TIMESTAMP'][ind] else 'H5F_CLOSE_WEAK',
        }
    file.access.file_image = {
            'use': file_agg[file_id]['file_size'] < AVAIL_NODE_MEMORY_BYTES,
            'buf_len': file_agg[file_id]['file_size']
    }
    file.access.optimization = {
            'use': True,
            'file_locking': not file_agg[file_id]['read-only'],
            'gc_ref': False, # TODO(hari) fix me
            'sieve_buf_size': 0 if not is_stride_used else file_agg[file_id]['ts_sum']*1.0/file_agg[file_id]['ts_count'],
            'small_data_block_size': 0 if file_agg[file_id]['file_size'] > GB else file_agg[file_id]['file_size'],
            'enable_object_flush_cb': True if not file_agg[file_id]['read-only'] else False
    }
    file.access.page_buffer = {
            'use': True,
            'buf_size': file_agg[file_id]['file_size'] if file_agg[file_id]['file_size'] < AVAIL_NODE_MEMORY_BYTES else AVAIL_NODE_MEMORY_BYTES,
            'min_meta_per': 100, # TODO(hari) fix me
            'min_raw_per': 100 if file_agg[file_id]['file_size'] < AVAIL_NODE_MEMORY_BYTES else int(file_agg[file_id]['file_size'] * 100.0 / AVAIL_NODE_MEMORY_BYTES),
    }
    file.creation.file_space = {
            'use': True,
            'file_space_page_size': file_agg[file_id]['ts_sum']*1.0/file_agg[file_id]['ts_count'],
            'strategy':1,
            'persist':True,
            'threshold':file_agg[file_id]['ts_sum']*1.0/file_agg[file_id]['ts_count'],
    }
    offset_bytes_needed = 0
    offset = file_agg[file_id]['ts_sum']
    while offset != 0:
        offset = offset >> 8;
        offset_bytes_needed = offset_bytes_needed + 1
    length_bytes_needed = 0
    ts = int(file_agg[file_id]['ts_sum']*1.0/file_agg[file_id]['ts_count'])
    while ts != 0:
        ts = ts >> 8;
        length_bytes_needed = length_bytes_needed + 1;
    
    file.creation.sizes = {
            'use': True,
            'sizeof_addr': offset_bytes_needed,
            'sizeof_size': length_bytes_needed + 1
    }
    configuration['files'][file.filename] = file

In [68]:
import numpy as np
import json
class NpEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        if isinstance(obj, np.floating):
            return float(obj)
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        if hasattr(obj,'json'):
            return obj.json()
        return super(NpEncoder, self).default(obj)

In [73]:
val = configuration

AttributeError: 'dict' object has no attribute 'json'

In [72]:
import json
print(json.dumps(val, cls=NpEncoder, indent=2))

TypeError: Object of type DataSet is not JSON serializable

In [80]:
val = str(configuration['/p/gpfs1/iopp/temp/h5bench/sync-write-2d-contig-contig/test.h5:/Timestep_2x'])
import json
print(json.dumps(json.loads(val), sort_keys=True, indent=2, separators=(',', ': ')))

JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

In [41]:
import math
math.log(16,3)

2.5237190142858297

In [33]:
characteristics = {}
for ind in h5d_df_c.index:
    file_id = h5d_df_c['id'][ind]
    characteristics[file_id] = {
        'dataset_name': report.data['name_records'][file_id],
        'io_size': h5d_df_c['H5D_BYTES_READ'][ind] + h5d_df_c['H5D_BYTES_WRITTEN'][ind],
        'read_bytes': h5d_df_c['H5D_BYTES_READ'][ind],
        'write_bytes': h5d_df_c['H5D_BYTES_WRITTEN'][ind],
    }
print(len(characteristics))

40

In [26]:
transfer_size_columns = []
for column in rel_mpiio_df_c.columns:
    if 'MPIIO_SIZE' in column:
        transfer_size_columns.append(column)
print(transfer_size_columns)

['MPIIO_SIZE_READ_AGG_0_100', 'MPIIO_SIZE_READ_AGG_100_1K', 'MPIIO_SIZE_READ_AGG_1K_10K', 'MPIIO_SIZE_READ_AGG_10K_100K', 'MPIIO_SIZE_READ_AGG_100K_1M', 'MPIIO_SIZE_READ_AGG_1M_4M', 'MPIIO_SIZE_READ_AGG_4M_10M', 'MPIIO_SIZE_READ_AGG_10M_100M', 'MPIIO_SIZE_READ_AGG_100M_1G', 'MPIIO_SIZE_READ_AGG_1G_PLUS', 'MPIIO_SIZE_WRITE_AGG_0_100', 'MPIIO_SIZE_WRITE_AGG_100_1K', 'MPIIO_SIZE_WRITE_AGG_1K_10K', 'MPIIO_SIZE_WRITE_AGG_10K_100K', 'MPIIO_SIZE_WRITE_AGG_100K_1M', 'MPIIO_SIZE_WRITE_AGG_1M_4M', 'MPIIO_SIZE_WRITE_AGG_4M_10M', 'MPIIO_SIZE_WRITE_AGG_10M_100M', 'MPIIO_SIZE_WRITE_AGG_100M_1G', 'MPIIO_SIZE_WRITE_AGG_1G_PLUS']

In [27]:
rel_mpiio_df_c[transfer_size_columns]

,MPIIO_SIZE_READ_AGG_0_100,MPIIO_SIZE_READ_AGG_100_1K,MPIIO_SIZE_READ_AGG_1K_10K,MPIIO_SIZE_READ_AGG_10K_100K,MPIIO_SIZE_READ_AGG_100K_1M,MPIIO_SIZE_READ_AGG_1M_4M,MPIIO_SIZE_READ_AGG_4M_10M,MPIIO_SIZE_READ_AGG_10M_100M,MPIIO_SIZE_READ_AGG_100M_1G,MPIIO_SIZE_READ_AGG_1G_PLUS,MPIIO_SIZE_WRITE_AGG_0_100,MPIIO_SIZE_WRITE_AGG_100_1K,MPIIO_SIZE_WRITE_AGG_1K_10K,MPIIO_SIZE_WRITE_AGG_10K_100K,MPIIO_SIZE_WRITE_AGG_100K_1M,MPIIO_SIZE_WRITE_AGG_1M_4M,MPIIO_SIZE_WRITE_AGG_4M_10M,MPIIO_SIZE_WRITE_AGG_10M_100M,MPIIO_SIZE_WRITE_AGG_100M_1G,MPIIO_SIZE_WRITE_AGG_1G_PLUS
0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,160,0,0

In [39]:
def value_to_int(x):
    if type(x) == float or type(x) == int:
        return x
    val = 1
    if 'K' in x:
        val = 1024
        if len(x) > 1:
            return int(x.replace('K', '')) * val
        return val
    if 'M' in x:
        val = 1024*1024
        if len(x) > 1:
            return float(x.replace('M', '')) * val
        return val
    if 'G' in x:
        val = 1024*1024*1024
        return float(x.replace('G', '')) * val
    return val
def convert(column):
    val = column.split("_")[-1]
    val_bytes = value_to_int(val)
    return val_bytes

In [44]:
average_ts = {}
average_read_ts = {}
average_write_ts = {}
for ind in rel_mpiio_df_c.index:
    file_id = rel_mpiio_df_c['id'][ind]
    average_ts[file_id] = {'count':0, 'sum':0}
    average_read_ts[file_id] ={'count':0, 'sum':0}
    average_write_ts[file_id] = {'count':0, 'sum':0}
    for column in transfer_size_columns:
        #print(ind, column, rel_mpiio_df_c[column][ind])
        val_bytes = convert(column)
        val_count = rel_mpiio_df_c[column][ind]
        average_ts[file_id]['sum'] = average_ts[file_id]['sum'] + val_bytes * val_count
        average_ts[file_id]['count'] = average_ts[file_id]['count'] + val_count
        if 'READ' in column:
            average_read_ts[file_id]['sum'] = average_read_ts[file_id]['sum'] + val_bytes * val_count
            average_read_ts[file_id]['count'] = average_read_ts[file_id]['count'] + val_count
        elif 'WRITE' in column:
            average_write_ts[file_id]['sum'] = average_write_ts[file_id]['sum'] + val_bytes * val_count
            average_write_ts[file_id]['count'] = average_write_ts[file_id]['count'] + val_count
    if average_ts[file_id]['count'] > 0:
        average_ts[file_id]['mean'] = average_ts[file_id]['sum'] / average_ts[file_id]['count']
    else:
        average_ts[file_id]['mean'] = 0
    if average_read_ts[file_id]['count'] > 0:
        average_read_ts[file_id]['mean'] = average_read_ts[file_id]['sum'] / average_read_ts[file_id]['count']
    else:
        average_read_ts[file_id]['mean'] = 0
    if average_write_ts[file_id]['count'] > 0:
        average_write_ts[file_id]['mean'] = average_write_ts[file_id]['sum'] / average_write_ts[file_id]['count']
    else:
        average_write_ts[file_id]['mean'] = 0
print(f"overall {average_ts}")
print(f"read {average_read_ts}")
print(f"write {average_write_ts}")

overall {836017519648718277: {'count': 164, 'sum': 16777256960.0, 'mean': 102300347.31707317}}
read {836017519648718277: {'count': 0, 'sum': 0.0, 'mean': 0}}
write {836017519648718277: {'count': 164, 'sum': 16777256960.0, 'mean': 102300347.31707317}}

In [46]:
io_size = {}
io_ops = {}
for fileid, val in average_ts.items():
    print(fileid, val)
    io_size[fileid] = val['sum']
    io_ops[fileid] = val['count']
print(io_size, io_ops)

836017519648718277 {'count': 164, 'sum': 16777256960.0, 'mean': 102300347.31707317}
{836017519648718277: 16777256960.0} {836017519648718277: 164}

In [47]:
# TODO(hari): get dataset_record from darshan HDF5
dataset_record = {'id':1, 'H5D_FILE_REC_ID':836017519648718277, 'H5D_DATATYPE_SIZE':4, }
dims = {836017519648718277: 3}